Treat proposals with no state as notAnswered
decidim-ice/decidim-module-decidim_awesome pull request #225
Opened 2023-07-18 10:20 UTC by marinamuca

Proposals in a null state were not being displayed on the Map.
![before](https://github.com/decidim-ice/decidim-module-decidim_awesome/assets/72018461/ad71c919-3033-4b21-b736-353a9ac4cbc1)
The problem has been resolved by treating the null state proposals as "notAnswered" ones, making them visible on the Map when the "Show not answered proposals" option is enabled in the configuration.
![after](https://github.com/decidim-ice/decidim-module-decidim_awesome/assets/72018461/e9f658a6-1762-46d0-a31f-6de3bd782c0c)

2023-07-18 10:26 UTC, fblupi requested changes
Could you include a test for this change, please?

2023-07-18 11:08 UTC, fblupi approved these changes

2023-07-28 09:36 UTC, microstudi requested changes
Thanks @marinamuca for this,
Please see if you can apply my review, it really needs a test. If not, I'll make and alternative PR solving this with the test.
In any case, thanks for the report, good catch!

2023-07-28 09:36 UTC, microstudi commented on app/packs/src/decidim/decidim_awesome/awesome_map/controllers/controller.js
> +        notAnswered && (node.state === "notAnswered" || node.state === null) ||
I'm thinking that maybe we can change the whole method here for something simpler:

```javascript
let checkProposalState = function (node, map) {
      const showConfig = map.config.show;
      return showConfig[node.state] || showConfig.notAnswered;
}
```

2023-07-28 09:36 UTC, microstudi commented on spec/system/awesome_map_spec.rb
> +  let!(:null_state_proposal) { create(:proposal, nil, component: proposal_component, latitude: 50, longitude: 10) }
```suggestion
  let!(:null_state_proposal) { create(:proposal, nil, component: proposal_component, latitude: 50, longitude: 10) }
```
This "nil" here won't work, symbols in rspec factories are "traits" that need to be registered. Passing "nil" is like doing nothing, it will create the default proposal.

This should work:
```suggestion
  let!(:null_state_proposal) { create(:proposal, state: nil, component: proposal_component, latitude: 50, longitude: 10) }
```

2023-07-28 09:36 UTC, microstudi commented on spec/system/awesome_map_spec.rb
> +  let!(:null_state_proposal) { create(:proposal, nil, component: proposal_component, latitude: 50, longitude: 10) }
Then, later on this file, you will want to make sure that the `null_state_propsal` is really displayed as a mark, this is done in the lines 111-114:
```ruby
  context "when step settings are all true" do
    it "shows all proposals markers" do
      sleep(1)
      expect(page.body).to have_selector("div[title='#{accepted_proposal.title["en"]}']")
      expect(page.body).to have_selector("div[title='#{evaluating_proposal.title["en"]}']")
      expect(page.body).to have_selector("div[title='#{rejected_proposal.title["en"]}']")
      expect(page.body).to have_selector("div[title='#{withdrawn_proposal.title["en"]}']")
      # check null are there:
      expect(page.body).to have_selector("div[title='#{null_state_propsal.title["en"]}']")
    end
  end
```

2023-07-31 10:27 UTC, fblupi approved these changes

2023-08-01 10:12 UTC, microstudi approved these changes
Thanks!

2023-08-01 10:12 UTC, merged