Upgrade auto-save for surveys and forms
decidim-ice/decidim-module-decidim_awesome pull request #280
Opened 2024-03-14 14:27 UTC by ElviaBth

🎩 What? Why?
Auto-save for surveys and forms.

📌 Related Issues
#/270 Upgrade 0.28 pending task 2.

📷 Screenshots

♥️ Thank you!

2024-03-16 08:15 UTC, microstudi requested changes
@ElviaBth  this PR needs more things

On one hand, it is introducing changes related to the integram chat, this should not be here (see some comments).

On the other hand, this feature is about saving temporary data on forms using the localstorage browser capabilities. This is done with the script "autosave.js"  (which uses https://github.com/appleple/form-storage in a npm package).

You need to:
1. [x] Upgrade the formstorage package (if possible) in package.json
2. [x] Adapt the `autosave.js` file so it removes jQuery dependencies
3. [x] Uncomment the import in the `decidim_application.js` file

Thanks!

2024-03-16 08:15 UTC, microstudi commented on app/views/decidim/decidim_awesome/admin/config/_constraints.html.erb
> +  <ul class="constraints-list<%= " inactive" if constraints&.detect{|c| c.settings["participatory_space_manifest"]=="none" } %>" style="padding: 0;">
```suggestion
  <ul class="constraints-list p-0<%= " inactive" if constraints&.detect{|c| c.settings["participatory_space_manifest"]=="none" } %>">
```
We can use tailwind here I think

2024-03-16 08:15 UTC, microstudi commented on spec/system/admin/admin_spec.rb
> -        skip "Live chat feature is pending to be adapted to Decidim 0.28 and currently is disabled at lib/decidim/decidim_awesome/awesome.rb"
This PR is not about intergram right? this should stay

2024-03-16 08:15 UTC, microstudi commented on lib/decidim/decidim_awesome/awesome.rb
> -      # false
this should not be here, this pr is not about intergram

2024-03-18 09:09 UTC, ElviaBth commented on lib/decidim/decidim_awesome/awesome.rb
> -      # false
Done

2024-03-18 09:13 UTC, ElviaBth commented on spec/system/admin/admin_spec.rb
> -        skip "Live chat feature is pending to be adapted to Decidim 0.28 and currently is disabled at lib/decidim/decidim_awesome/awesome.rb"
Done

2024-03-18 09:21 UTC, ElviaBth commented on app/views/decidim/decidim_awesome/admin/config/_constraints.html.erb
> +  <ul class="constraints-list<%= " inactive" if constraints&.detect{|c| c.settings["participatory_space_manifest"]=="none" } %>" style="padding: 0;">
Done

2024-03-20 15:05 UTC, merged