Create custom styles for admin
decidim-ice/decidim-module-decidim_awesome pull request #337
Opened 2024-10-16 10:53 UTC by ElviaBth

2024-10-21 11:37 UTC, microstudi requested changes
Good job.

To finish it, please check the comments, there are some inconsistencies in the constrains plural names.

On the other hand, the spec `spec/system/admin/admin_manages_scoped_admin_styles_spec.rb` is repeating a lot of code, from `spec/system/admin/admin_manages_scoped_styles_spec.rb`. Can you do the same as is done in  `spec/system/admin/admin_manages_proposal_custom_fields_spec.rb` using shared examples?

And, finally, please update the screenshots and explanations from the README.md file. Probably editing the point 8 with two subsection 8.1 (public styles) and 8.2 (admin styles)

2024-10-21 11:37 UTC, microstudi commented on app/overrides/layouts/decidim/admin/_header/add_awesome_tags.html.erb.deface
> +<% append_stylesheet_pack_tag "decidim_decidim_awesome", media: "all" %>
this is the admin, I think this line does not belong here

2024-10-21 11:37 UTC, microstudi commented on spec/commands/admin/destroy_scoped_style_spec.rb
> +          expect(AwesomeConfig.find_by(organization:, var: :scoped_styles_foo)).to be_nil
```suggestion
          expect(AwesomeConfig.find_by(organization:, var: :scoped_style_foo)).to be_nil
```

sub-vars are always singular

2024-10-21 11:37 UTC, microstudi commented on spec/system/admin/admin_manages_scoped_admin_styles_spec.rb
> +        expect(Decidim::DecidimAwesome::AwesomeConfig.find_by(organization:, var: :scoped_admin_styles_bar)).to be_present
```suggestion
        expect(Decidim::DecidimAwesome::AwesomeConfig.find_by(organization:, var: :scoped_admin_style_bar)).to be_present
```

singular

2024-10-21 11:37 UTC, microstudi commented on spec/system/admin/admin_manages_scoped_admin_styles_spec.rb
> +        expect(Decidim::DecidimAwesome::AwesomeConfig.find_by(organization:, var: :scoped_admin_styles_bar).constraints.first.settings).to eq("participatory_space_manifest" => "participatory_processe
```suggestion
        expect(Decidim::DecidimAwesome::AwesomeConfig.find_by(organization:, var: :scoped_admin_style_bar)).to be_present
        expect(Decidim::DecidimAwesome::AwesomeConfig.find_by(organization:, var: :scoped_admin_style_bar).constraints.first.settings).to eq("participatory_space_manifest" => "participatory_processes")
```
Singular

2024-10-21 11:37 UTC, microstudi commented on spec/system/admin/admin_manages_scoped_admin_styles_spec.rb
> +          expect(Decidim::DecidimAwesome::AwesomeConfig.find_by(organization:, var: :scoped_admin_style_bar).constraints).not_to be_present
```suggestion
          expect(Decidim::DecidimAwesome::AwesomeConfig.find_by(organization:, var: :scoped_admin_style_bar)).to be_present
          expect(Decidim::DecidimAwesome::AwesomeConfig.find_by(organization:, var: :scoped_admin_style_bar).constraints).not_to be_present
```
singular

2024-10-21 11:37 UTC, microstudi commented on spec/system/admin/admin_manages_scoped_styles_spec.rb
> +        expect(Decidim::DecidimAwesome::AwesomeConfig.find_by(organization:, var: :scoped_styles_bar)).to be_present
```suggestion
        expect(Decidim::DecidimAwesome::AwesomeConfig.find_by(organization:, var: :scoped_style_bar)).to be_present
```

2024-10-21 11:37 UTC, microstudi commented on spec/system/admin/admin_manages_scoped_styles_spec.rb
> +        expect(Decidim::DecidimAwesome::AwesomeConfig.find_by(organization:, var: :scoped_styles_bar).constraints.first.settings).to eq("participatory_space_manifest" => "participatory_processes")
```suggestion
        expect(Decidim::DecidimAwesome::AwesomeConfig.find_by(organization:, var: :scoped_style_bar)).to be_present
        expect(Decidim::DecidimAwesome::AwesomeConfig.find_by(organization:, var: :scoped_style_bar).constraints.first.settings).to eq("participatory_space_manifest" => "participatory_processes")
```

2024-10-21 11:37 UTC, microstudi commented on spec/system/admin/admin_manages_scoped_styles_spec.rb
> +          expect(Decidim::DecidimAwesome::AwesomeConfig.find_by(organization:, var: :scoped_styles_bar)).to be_present
```suggestion
          expect(Decidim::DecidimAwesome::AwesomeConfig.find_by(organization:, var: :scoped_style_bar)).to be_present
```

2024-10-21 11:39 UTC, ElviaBth commented on spec/system/admin/admin_manages_scoped_styles_spec.rb
> +        expect(Decidim::DecidimAwesome::AwesomeConfig.find_by(organization:, var: :scoped_styles_bar).constraints.first.settings).to eq("participatory_space_manifest" => "participatory_processes")
Done

2024-10-21 11:40 UTC, ElviaBth commented on spec/system/admin/admin_manages_scoped_styles_spec.rb
> +        expect(Decidim::DecidimAwesome::AwesomeConfig.find_by(organization:, var: :scoped_styles_bar)).to be_present
Done

2024-10-21 11:41 UTC, ElviaBth commented on spec/system/admin/admin_manages_scoped_styles_spec.rb
> +          expect(Decidim::DecidimAwesome::AwesomeConfig.find_by(organization:, var: :scoped_styles_bar)).to be_present
Done

2024-10-21 13:45 UTC, ElviaBth commented on spec/system/admin/admin_manages_scoped_admin_styles_spec.rb
> +          expect(Decidim::DecidimAwesome::AwesomeConfig.find_by(organization:, var: :scoped_admin_style_bar).constraints).not_to be_present
Done

2024-10-21 13:45 UTC, ElviaBth commented on spec/system/admin/admin_manages_scoped_admin_styles_spec.rb
> +        expect(Decidim::DecidimAwesome::AwesomeConfig.find_by(organization:, var: :scoped_admin_styles_bar).constraints.first.settings).to eq("participatory_space_manifest" => "participatory_processe
Done

2024-10-21 13:45 UTC, ElviaBth commented on spec/system/admin/admin_manages_scoped_admin_styles_spec.rb
> +        expect(Decidim::DecidimAwesome::AwesomeConfig.find_by(organization:, var: :scoped_admin_styles_bar)).to be_present
Done

2024-10-21 13:52 UTC, ElviaBth commented on app/overrides/layouts/decidim/admin/_header/add_awesome_tags.html.erb.deface
> +<% append_stylesheet_pack_tag "decidim_decidim_awesome", media: "all" %>
Done

2024-10-21 13:59 UTC, ElviaBth commented on spec/commands/admin/destroy_scoped_style_spec.rb
> +          expect(AwesomeConfig.find_by(organization:, var: :scoped_styles_foo)).to be_nil
Done

2024-10-29 10:38 UTC, microstudi commented on app/overrides/layouts/decidim/admin/_header/add_awesome_tags.html.erb.deface
> +<%= render(partial: "layouts/decidim/decidim_awesome/admin/custom_styles") if awesome_scoped_admin_styles.present? %>
```suggestion
```
Let's remove this from this file and create a new deface file:

```
<!-- insert_after "erb[loud]:contains('stylesheet_pack_tag("decidim_core", "decidim_admin")')" -->

<%= render(partial: "layouts/decidim/decidim_awesome/admin/custom_styles") if awesome_scoped_admin_styles.present? %>

```

2024-10-29 10:55 UTC, microstudi commented on app/overrides/layouts/decidim/admin/_header/add_awesome_custom_styles.html.erb.deface
> +<!-- insert_after "erb[loud]:contains('stylesheet_pack_tag("decidim_core", "decidim_admin")')" -->
```suggestion
<!-- insert_after "erb[loud]:contains('snippets.display(:head)')" -->
```

2024-10-29 11:01 UTC, ElviaBth commented on app/overrides/layouts/decidim/admin/_header/add_awesome_tags.html.erb.deface
> +<%= render(partial: "layouts/decidim/decidim_awesome/admin/custom_styles") if awesome_scoped_admin_styles.present? %>
Done

2024-10-29 11:01 UTC, ElviaBth commented on app/overrides/layouts/decidim/admin/_header/add_awesome_custom_styles.html.erb.deface
> +<!-- insert_after "erb[loud]:contains('stylesheet_pack_tag("decidim_core", "decidim_admin")')" -->
Done

2024-10-29 11:45 UTC, microstudi approved these changes
great work!

2024-10-29 11:45 UTC, merged